version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
  server:
    image: ls-yolov8-backend:0.1.0
    container_name: label-studio-ml
    build: .
    environment:
      - PYTHONUNBUFFERED=0
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LABEL_STUDIO_USE_REDIS=true
      - MODEL_DIR=/data/models
      - MODEL_TYPE=det
      - MODEL_FILE_PATH=/data/models/best.pt
      - LS_URL=http://192.168.99.111:8080
      - LS_API_TOKEN=9d847b67a229c86b8ce74600808bc53c104112ea

    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/models:/data/models"
